"""Contracts for the medical Graph-RAG research pipeline.

The production baseline remains under :mod:`medhorizon_videorag.pipelines.baseline`.
The first runnable builder creates a conservative, per-video evidence graph
from observation-first clip descriptions. A deterministic event retriever provides
the first auditable retrieval baseline without changing the production pipeline.
"""

from .evidence_builder import (
    ACTION_VOCABULARY,
    BUILDER_VERSION,
    ENTITY_VOCABULARY,
    EVENT_SUPPORT_VERSION,
    GRAPH_SCHEMA_VERSION,
    REPRESENTATIVE_EVIDENCE_VERSION,
    EvidenceGraphArtifacts,
    NormalizedAction,
    NormalizedClip,
    NormalizedMention,
    TemporalEvent,
    build_evidence_graph,
    load_description_rows,
    load_manifest_frame_paths,
    merge_temporal_events,
    normalize_action,
    normalize_description_rows,
    normalize_entity,
    write_evidence_graph_artifacts,
)
from .ports import EvidenceVerifier, GraphBuilder, GraphRetriever, GraphStore
from .qa_experiment import (
    GRAPH_QA_EXPERIMENT_VERSION,
    OpenAICompatibleGraphQA,
    build_event_observation_catalog,
    select_event_frame_groups,
    strip_explicit_time_range,
)
from .retrieval import (
    RETRIEVER_VERSION,
    DeterministicEventGraphRetriever,
    NormalizedGraphQuery,
    load_evidence_graph,
    normalize_graph_query,
)
from .schemas import (
    EvidenceInterval,
    GraphEdge,
    GraphNode,
    GraphRetrievalResult,
    MedicalGraphQAExample,
    VideoEvidenceGraph,
)
from .semantic_layer import (
    APPEARANCE_TRACK_VERSION,
    SEMANTIC_GRAPH_SCHEMA_VERSION,
    SEMANTIC_LAYER_VERSION,
    SemanticLayerArtifacts,
    augment_with_semantic_hypotheses,
    build_video_semantic_ontology,
    extract_phase_name,
    load_semantic_hypotheses,
    retrieve_phase_boundary_instruments,
    write_semantic_layer_artifacts,
)
from .sequence_phase import (
    SEQUENCE_PHASE_VERSION,
    TWO_STAGE_SEQUENCE_PHASE_VERSION,
    build_open_activity_segmentation_prompt,
    build_sequence_phase_prompt,
    build_strict_phase_mapping_prompt,
    compact_observation_sequence,
    load_observation_sequence,
    normalize_open_activity_response,
    normalize_sequence_phase_response,
    normalize_strict_phase_mapping_response,
    project_sequence_phases_to_events,
)

__all__ = [
    "ACTION_VOCABULARY",
    "APPEARANCE_TRACK_VERSION",
    "BUILDER_VERSION",
    "ENTITY_VOCABULARY",
    "EVENT_SUPPORT_VERSION",
    "GRAPH_QA_EXPERIMENT_VERSION",
    "GRAPH_SCHEMA_VERSION",
    "REPRESENTATIVE_EVIDENCE_VERSION",
    "RETRIEVER_VERSION",
    "SEMANTIC_GRAPH_SCHEMA_VERSION",
    "SEMANTIC_LAYER_VERSION",
    "SEQUENCE_PHASE_VERSION",
    "TWO_STAGE_SEQUENCE_PHASE_VERSION",
    "DeterministicEventGraphRetriever",
    "EvidenceGraphArtifacts",
    "EvidenceInterval",
    "EvidenceVerifier",
    "GraphBuilder",
    "GraphEdge",
    "GraphNode",
    "GraphRetrievalResult",
    "GraphRetriever",
    "GraphStore",
    "MedicalGraphQAExample",
    "NormalizedAction",
    "NormalizedClip",
    "NormalizedGraphQuery",
    "NormalizedMention",
    "OpenAICompatibleGraphQA",
    "SemanticLayerArtifacts",
    "TemporalEvent",
    "VideoEvidenceGraph",
    "augment_with_semantic_hypotheses",
    "build_event_observation_catalog",
    "build_evidence_graph",
    "build_open_activity_segmentation_prompt",
    "build_sequence_phase_prompt",
    "build_strict_phase_mapping_prompt",
    "build_video_semantic_ontology",
    "compact_observation_sequence",
    "extract_phase_name",
    "load_description_rows",
    "load_evidence_graph",
    "load_manifest_frame_paths",
    "load_observation_sequence",
    "load_semantic_hypotheses",
    "merge_temporal_events",
    "normalize_action",
    "normalize_description_rows",
    "normalize_entity",
    "normalize_graph_query",
    "normalize_open_activity_response",
    "normalize_sequence_phase_response",
    "normalize_strict_phase_mapping_response",
    "project_sequence_phases_to_events",
    "retrieve_phase_boundary_instruments",
    "select_event_frame_groups",
    "strip_explicit_time_range",
    "write_evidence_graph_artifacts",
    "write_semantic_layer_artifacts",
]
